create or replace secure view INNOWISE_SNOWFLAKE_LMS.STAGE3.SECURE_AIRLINES_FACT(
	PASSENGERID,
	FIRSTNAME,
	LASTNAME,
	GENDER,
	AGE,
	NATIONALITY,
	AIRPORTNAME,
	AIRPORTCOUNTRYCODE,
	COUNTRYNAME,
	AIRPORTCONTINENT,
	CONTINENTS,
	DEPARTUREDATE,
	ARRIVALAIRPORT,
	PILOTNAME,
	FLIGHTSTATUS,
	TICKETTYPE,
	PASSENGERSTATUS
) WITH ROW ACCESS POLICY INNOWISE_SNOWFLAKE_LMS.STAGE3.AIRLINE_POLICY ON (PASSENGERID)
 as
SELECT * FROM stage2.airlines;