create or replace database INNOWISE_SNOWFLAKE_LMS;

create or replace schema INNOWISE_SNOWFLAKE_LMS.PUBLIC;

create or replace schema INNOWISE_SNOWFLAKE_LMS.STAGE1;

create or replace TABLE INNOWISE_SNOWFLAKE_LMS.STAGE1.AIRLINES (
	PASSENGERID VARCHAR(16777216),
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	GENDER VARCHAR(16777216),
	AGE VARCHAR(16777216),
	NATIONALITY VARCHAR(16777216),
	AIRPORTNAME VARCHAR(16777216),
	AIRPORTCOUNTRYCODE VARCHAR(16777216),
	COUNTRYNAME VARCHAR(16777216),
	AIRPORTCONTINENT VARCHAR(16777216),
	CONTINENTS VARCHAR(16777216),
	DEPARTUREDATE VARCHAR(16777216),
	ARRIVALAIRPORT VARCHAR(16777216),
	PILOTNAME VARCHAR(16777216),
	FLIGHTSTATUS VARCHAR(16777216),
	TICKETTYPE VARCHAR(16777216),
	PASSENGERSTATUS VARCHAR(16777216)
);
CREATE OR REPLACE FILE FORMAT INNOWISE_SNOWFLAKE_LMS.STAGE1.CSV_FORMAT
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	NULL_IF = ('', 'NULL')
;
create or replace stream INNOWISE_SNOWFLAKE_LMS.STAGE1.AIRLINE_STREAM on table AIRLINES;
create or replace schema INNOWISE_SNOWFLAKE_LMS.STAGE2;

create or replace TABLE INNOWISE_SNOWFLAKE_LMS.STAGE2.AIRLINES (
	PASSENGERID VARCHAR(16777216) NOT NULL,
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	GENDER VARCHAR(16777216),
	AGE NUMBER(38,0),
	NATIONALITY VARCHAR(16777216),
	AIRPORTNAME VARCHAR(16777216),
	AIRPORTCOUNTRYCODE VARCHAR(2),
	COUNTRYNAME VARCHAR(16777216),
	AIRPORTCONTINENT VARCHAR(3),
	CONTINENTS VARCHAR(16777216),
	DEPARTUREDATE DATE,
	ARRIVALAIRPORT VARCHAR(3),
	PILOTNAME VARCHAR(16777216),
	FLIGHTSTATUS VARCHAR(16777216),
	TICKETTYPE VARCHAR(16777216),
	PASSENGERSTATUS VARCHAR(16777216),
	primary key (PASSENGERID)
);
create or replace TABLE INNOWISE_SNOWFLAKE_LMS.STAGE2.AIRLINES_RESTORED (
	PASSENGERID VARCHAR(16777216) NOT NULL,
	FIRSTNAME VARCHAR(16777216),
	LASTNAME VARCHAR(16777216),
	GENDER VARCHAR(16777216),
	AGE NUMBER(38,0),
	NATIONALITY VARCHAR(16777216),
	AIRPORTNAME VARCHAR(16777216),
	AIRPORTCOUNTRYCODE VARCHAR(2),
	COUNTRYNAME VARCHAR(16777216),
	AIRPORTCONTINENT VARCHAR(3),
	CONTINENTS VARCHAR(16777216),
	DEPARTUREDATE DATE,
	ARRIVALAIRPORT VARCHAR(3),
	PILOTNAME VARCHAR(16777216),
	FLIGHTSTATUS VARCHAR(16777216),
	TICKETTYPE VARCHAR(16777216),
	PASSENGERSTATUS VARCHAR(16777216),
	primary key (PASSENGERID)
);
create or replace TABLE INNOWISE_SNOWFLAKE_LMS.STAGE2.AUDIT (
	PIPELINENAME VARCHAR(16777216),
	SOURCESTAGE VARCHAR(16777216),
	TARGETSTAGE VARCHAR(16777216),
	ROWSINSERTED NUMBER(38,0),
	EXECUTIONTIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE PROCEDURE INNOWISE_SNOWFLAKE_LMS.STAGE2.LOAD_CLEAN_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    LET rows_inserted INT := 0;
    BEGIN TRANSACTION;

    INSERT INTO stage2.airlines
    SELECT 
        PassengerID, FirstName, LastName, Gender, CAST(Age as INT), Nationality, AirportName, AirportCountryCode, CountryName,
        AirportContinent, Continents, TO_DATE(DepartureDate, ''MM/DD/YYYY''), ArrivalAirport, PilotName, FlightStatus,
        TicketType, PassengerStatus
    FROM stage1.airline_stream;

    rows_inserted := SQLROWCOUNT;

    COMMIT;

    RETURN TO_VARCHAR(rows_inserted);

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RETURN 0;
END;
';
create or replace stream INNOWISE_SNOWFLAKE_LMS.STAGE2.AIRLINES_STREAM on table AIRLINES;
create or replace schema INNOWISE_SNOWFLAKE_LMS.STAGE3;

create or replace TABLE INNOWISE_SNOWFLAKE_LMS.STAGE3.VISITORS_PER_MONTH (
	DESTINATIONCOUNTRY VARCHAR(16777216),
	TRAVELMONTH VARCHAR(16777216),
	TOTALVISITORS NUMBER(38,0),
	AVERAGEPASSENGERAGE NUMBER(5,2),
	LASTUPDATED TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
create or replace secure view INNOWISE_SNOWFLAKE_LMS.STAGE3.SECURE_AIRLINES_FACT(
	PASSENGERID,
	FIRSTNAME,
	LASTNAME,
	GENDER,
	AGE,
	NATIONALITY,
	AIRPORTNAME,
	AIRPORTCOUNTRYCODE,
	COUNTRYNAME,
	AIRPORTCONTINENT,
	CONTINENTS,
	DEPARTUREDATE,
	ARRIVALAIRPORT,
	PILOTNAME,
	FLIGHTSTATUS,
	TICKETTYPE,
	PASSENGERSTATUS
) WITH ROW ACCESS POLICY INNOWISE_SNOWFLAKE_LMS.STAGE3.AIRLINE_POLICY ON (PASSENGERID)
 as
SELECT * FROM stage2.airlines;
CREATE OR REPLACE PROCEDURE INNOWISE_SNOWFLAKE_LMS.STAGE3.LOAD_MONTHLY_VISITORS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    LET rows_affected INT := 0;
    BEGIN TRANSACTION;
    
    INSERT INTO stage3.visitors_per_month (
        DestinationCountry, TravelMonth, TotalVisitors, AveragePassengerAge)
    SELECT CountryName, TO_CHAR(DepartureDate, ''YYYY-MM'') as TravelMonth, 
        COUNT(PassengerID) as TotalVisitors, AVG(Age) as AveragePassengerAge
    FROM stage2.airlines_stream
    GROUP BY CountryName, TO_CHAR(DepartureDate, ''YYYY-MM'');

    rows_affected := SQLROWCOUNT;
    COMMIT;

    RETURN TO_VARCHAR(rows_affected);
END;
';
create or replace row access policy INNOWISE_SNOWFLAKE_LMS.STAGE3.AIRLINE_POLICY as (CURRENT_ROLE VARCHAR) 
returns BOOLEAN ->
CURRENT_ROLE() = 'ACCOUNTADMIN'
;