create or replace TABLE INNOWISE_SNOWFLAKE_LMS.STAGE3.VISITORS_PER_MONTH (
	DESTINATIONCOUNTRY VARCHAR(16777216),
	TRAVELMONTH VARCHAR(16777216),
	TOTALVISITORS NUMBER(38,0),
	AVERAGEPASSENGERAGE NUMBER(5,2),
	LASTUPDATED TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);